# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-raspberrypi-local"
BBFILE_PATTERN_meta-raspberrypi-local = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-raspberrypi-local = "6"

LICENSE_PATH += "${LAYERDIR}/"

LAYERSERIES_COMPAT_meta-raspberrypi-local = "wrynose"
