[config]
version = "2"

[data]
path = "/data/tedge/data"

[logs]
path = "/data/tedge/log"

[software.plugin]
exclude = "^(glibc|lib|kernel-|iptables-module|util-linux|packagegroup-|pam-plugin-|alsa-|linux-firmware-|bluez-firmware-|e2fsprogs).*"
