#!/bin/sh
set -eu

IDENTITY_PREFIX=

get_mac_address() {
    SCN=/sys/class/net
    min=65535
    arphrd_ether=1
    ifdev=

    # find iface with lowest ifindex, skip non ARPHRD_ETHER types (lo, sit ...)
    for dev in "$SCN"/*; do
        if [ ! -f "$dev/type" ]; then
            continue
        fi

        iftype=$(cat "$dev/type")
        if [ "$iftype" -ne $arphrd_ether ]; then
            continue
        fi

        # Skip dummy interfaces
        if echo "$dev" | grep -q "$SCN/dummy" 2>/dev/null; then
            continue
        fi

        idx=$(cat "$dev/ifindex")
        if [ "$idx" -lt "$min" ]; then
            min=$idx
            ifdev=$dev
        fi
    done

    if [ -z "$ifdev" ]; then
        echo "no suitable interfaces found" >&2
        exit 1
    else
        echo "using interface $ifdev" >&2
        # grab MAC address
        cat "$ifdev/address"
    fi
}

read_from_build_file() {
    PROPERTY="$1"
    if [ ! -f /etc/build ]; then
        return 1
    fi
    value=$(grep "^$PROPERTY =" /etc/build | cut -d= -f2- | xargs)
    if [ -z "$value" ]; then
        return 1
    fi
    echo "$value"

    echo "Reading the model prefix from the $PROPERTY property of /etc/build" >&2
}

get_model_type() {
    # Use explicit value if one is defined in the build file
    MODEL_PREFIX=$(read_from_build_file DEVICE_MODEL ||:)
    if [ -n "$MODEL_PREFIX" ]; then
        echo "$MODEL_PREFIX"
        return 0
    fi

    MODEL=$(grep Model /proc/cpuinfo | cut -d: -f2 | xargs)
    SERIAL_NO=$(grep Serial /proc/cpuinfo | cut -d: -f2 | xargs)

    echo "Detected model: $MODEL" >&2
    echo "Detected serial no.: $SERIAL_NO" >&2

    MODEL_PREFIX=

    case "$MODEL" in
        Raspberry\ Pi\ 5*)
            MODEL_PREFIX=rpi5
            ;;
        Raspberry\ Pi\ 4*)
            MODEL_PREFIX=rpi4
            ;;
        Raspberry\ Pi\ 3*)
            MODEL_PREFIX=rpi3
            ;;
        Raspberry\ Pi\ 2*)
            MODEL_PREFIX=rpi2
            ;;
        Raspberry\ Pi\ Model*)
            MODEL_PREFIX=rpi1
            ;;
        Raspberry\ Pi\ Zero\ 2\ W\ Rev*)
            MODEL_PREFIX=rpizero2
            ;;
        Raspberry\ Pi\ Zero\ W\ Rev*)
            MODEL_PREFIX=rpizero
            ;;
        Raspberry\ Pi\ Compute\ Module\ 3*)
            MODEL_PREFIX=rpicm3
            ;;
        Raspberry\ Pi\ Compute\ Module\ 4*)
            MODEL_PREFIX=rpicm4
            ;;
        *)
            # Use the first non empty value from the build file with a fallback if it is not found
            MODEL_PREFIX=$(read_from_build_file MACHINE || echo "tedge")
            ;;
    esac
    echo "$MODEL_PREFIX"
}

MAC_ADDR=$(get_mac_address)
MODEL=$(get_model_type)

IDENTITY=

if [ -n "$IDENTITY_PREFIX" ]; then
    echo "Using identity prefix: $IDENTITY_PREFIX" >&2
    IDENTITY=$(echo "${IDENTITY_PREFIX}-${MODEL}-${MAC_ADDR}" | tr -d ":")
else
    IDENTITY=$(echo "${MODEL}-${MAC_ADDR}" | tr -d ":")
fi

echo "$IDENTITY"