#!/bin/sh
set -e

RAN_MARKER=/etc/tedge/.bootstrapped

log() {
    echo "$@" >&2
}

init_tedge_data() {
    # Create data persistence folders
    # Ensure persistence of operation state across partition swaps by storing
    # information on a persisted mount
    DATA_DIR="${DATA_DIR:-/data}"
    if [ -d "$DATA_DIR" ]; then
        log "Creating tedge persistence folder under $DATA_DIR/tedge"

        if [ -d /etc/tedge-default ]; then
            log "Copying files from /etc/tedge-default to $DATA_DIR/tedge"
            cp -rp /etc/tedge-default "$DATA_DIR/tedge"
        fi

        mkdir -p "$DATA_DIR/tedge"
        mkdir -p "$DATA_DIR/tedge/log"
        mkdir -p "$DATA_DIR/tedge/agent"
        chown -Rh tedge:tedge "$DATA_DIR/tedge"

        log "Creating tedge persistence folder under $DATA_DIR/mosquitto"
        mkdir -p "$DATA_DIR/mosquitto"
        chown -Rh mosquitto:mosquitto "$DATA_DIR/mosquitto"
    fi
}

set_hostname() {
    host_name="$1"
    if [ "$(cat /etc/hostname)" = "$host_name" ]; then
        echo "Host name is already set"
        return
    fi

    if [ -w /etc/hostname ]; then
        echo "$host_name" | tee /etc/hostname
    else
        echo "Skipping setting hostname as /etc/hostname is not writable"
    fi

    if [ -w /etc/hosts ]; then
        sed -i -E 's/^127.0.1.1.*/127.0.1.1\t'"$host_name"'/' /etc/hosts
    else
        echo "Skipping setting hosts as /etc/hosts is not writable"
    fi

    if [ -w /etc/hostname ]; then
        hostnamectl set-hostname "$host_name" || log "Failed to set using hostnamectl"
    else
        echo "Skipping setting hostname via hostnamectl set-hostname as /etc/hostname is not writable"
    fi

    if command -V systemctl >/dev/null 2>&1; then
        systemctl restart avahi-daemon --no-block 2>/dev/null ||:
    fi
}

# set hostname
DEVICE_ID=
attempt=0
while [ "$attempt" -lt 30 ]; do
    DEVICE_ID="$(tedge-identity ||:)"
    if [ -n "$DEVICE_ID" ]; then
        log "Found valid DEVICE_ID"
        break
    fi
    attempt=$((attempt + 1))
    log "Waiting for tedge-identity"
    sleep 5
done

init_tedge_data

set_hostname "$DEVICE_ID"

touch "$RAN_MARKER"
