#!/bin/sh
set -e
echo "state-script version: 5" >&2

# Use trap to unmount in case of unexpected errors
# unmount using mountpoint rather than device (in case it is mounted elsewhere)
trap_exit() {
    echo "Unmounting"
    sync "/tmp/inactive_part" ||:

    # TODO: calling umount hangs here!
    umount -l /tmp/inactive_part &
    i=0
    while [ "$i" -lt 5 ]; do
        if ! mountpoint -q /tmp/inactive_part; then
            echo "inactive partition has been unmounted"
            break
        fi
        i=$((i + 1))
        sleep 1
    done
    # Force killing of any user using the mount (which might cause shutdown stalling)
    fuser -mk /tmp/inactive_part ||:
}
trap trap_exit EXIT

progress() {
    echo "$@"
    echo "$@" >&2
}

MENDER_ROOTFS_PART_A="/dev/mmcblk0p2"
MENDER_ROOTFS_PART_B="/dev/mmcblk0p3"

#
# Retain ssh server keys from the current root
#
if mount | grep "${MENDER_ROOTFS_PART_A} on / "; then
  inactive_part="${MENDER_ROOTFS_PART_B}"
else
  inactive_part="${MENDER_ROOTFS_PART_A}"
fi

target="/tmp/inactive_part"
progress "Mounting ${inactive_part} to ${target}"
mkdir -p "${target}"

# DEBUG: Wait before mounting (to give time for the partition write to finish?)
sleep 5
# mount -o ro ${inactive_part} /tmp/inactive_part
mount ${inactive_part} "${target}"
progress "Mounted ${inactive_part} to ${target}"

# Save core services as presets
progress "Saving presets"

# Note: ||: is needed as this can fail if the file does not exist (even when using rm -f!)
# This might be a combination of a busybox thing and/or the way the volume is mounted
rm -f "${target}/etc/systemd/system-preset/98-thin-edge.preset" ||:
mkdir -p "${target}/etc/systemd/system-preset"
systemctl list-unit-files | grep enabled | grep -E "^tedge|^c8y|^mosquitto" | cut -d\  -f1 | while read -r UNIT_NAME; do
    progress "Adding $UNIT_NAME to service preset"
    echo "enable $UNIT_NAME" >> "${target}/etc/systemd/system-preset/98-thin-edge.preset"
done


# WORKAROUND: Copy systemd symlinks so that the agent is enable by default
# Check if this causes a problem if the service does not exist in the new image
if [ -e /etc/systemd/system/multi-user.target.wants/tedge-agent.service ]; then
    progress "Copying thin-edge.io services symlink to enable services on startup"

    if ls /etc/systemd/system/multi-user.target.wants/tedge* >/dev/null 2>&1; then
        cp -af /etc/systemd/system/multi-user.target.wants/tedge* "${target}/etc/systemd/system/multi-user.target.wants/" || {
            progress "Failed to copy tedge* services"
            exit 1
        }
    fi

    if ls /etc/systemd/system/multi-user.target.wants/c8y* >/dev/null 2>&1; then
        cp -af /etc/systemd/system/multi-user.target.wants/c8y* "${target}/etc/systemd/system/multi-user.target.wants/" || {
            progress "Failed to copy c8y* services"
            exit 1
        }
    fi
fi

# sudoers
if [ -d /etc/sudoers.d ]; then
    progress "Copying sudoers.d config"
    cp -af /etc/sudoers.d/* "${target}/etc/sudoers.d/"
fi

# mosquitto
# Due to a race condition
# if [ -d /var/lib/mosquitto ]; then
#     # TODO: Check if mosquitto should be stopped instead
#     # Tell mosquitto to write to file before copying the db
#     progress "Sending SIGUSR1 to mosquitto to force writing to db (then wait a few seconds)"
#     systemctl kill --signal=SIGUSR1 mosquitto.service
#     sleep 5

#     progress "Copying mosquitto db"
#     mkdir -p "${target}/var/lib/mosquitto"
#     chown -R mosquitto:mosquitto "${target}/var/lib/mosquitto"
#     if ls /var/lib/mosquitto/* >/dev/null 2>&1; then
#         cp -Rfa /var/lib/mosquitto/* "${target}/var/lib/mosquitto"
#     fi
# fi

# tedge files
if [ -d /etc/tedge ]; then
    progress "Copying /etc/tedge"
    if [ ! -d "${target}/etc/tedge" ]; then
        mkdir -p "${target}/etc/tedge"
        chown tedge:tedge "${target}/etc/tedge"
    fi

    if ls /etc/tedge/* >/dev/null 2>&1; then
        progress "Copying /etc/tedge configuration"
        cp -RfaH /etc/tedge/* "${target}/etc/tedge"
    fi

    # data files
    VAR_TEDGE=$(tedge config get data.path)
    NEW_VAR_TEDGE="${target}${VAR_TEDGE}"

    progress "Copying $VAR_TEDGE"
    if [ ! -d "$NEW_VAR_TEDGE" ]; then
        mkdir -p "$NEW_VAR_TEDGE"
        chown tedge:tedge "$NEW_VAR_TEDGE"
    fi
    if ls "$VAR_TEDGE"/* >/dev/null 2>&1; then
        progress "Copying $VAR_TEDGE files"
        cp -Rfa "$VAR_TEDGE"/* "$NEW_VAR_TEDGE"
    fi
fi

# ssh authorized keys
if [ -d /home/root/.ssh ]; then
    if [ -f /home/root/.ssh/authorized_keys ]; then
        if [ ! -f "${target}/home/root/.ssh/authorized_keys" ]; then
            progress "Copying authorized_keys"
            mkdir -p "${target}/home/root/.ssh"
            chmod 700 "${target}/home/root/.ssh"

            if ls "/home/root/.ssh/"* >/dev/null 2>&1; then
                progress "Copying /home/root/.ssh/* files"
                cp -Rfa /home/root/.ssh/* "${target}/home/root/.ssh/"
            fi
        else
            progress "Found authorized_keys in new root, skipping copy"
        fi
    else
        progress "No authorized keys in current root, skipping copy"
    fi
fi

# ssh configuration
SSH_SERVER_DIR=
if [ -d "${target}/etc/ssh" ]; then
    SSH_SERVER_DIR=etc/ssh
elif [ -d "${target}/etc/dropbear" ]; then
    SSH_SERVER_DIR=etc/dropbear
fi

if [ -n "$SSH_SERVER_DIR" ]; then
    keys=$(ls -l "${target}/${SSH_SERVER_DIR}"/*key* 2>/dev/null | wc -l)

    if [ "$keys" -eq 0 ]; then
        progress "Copying ssh server key (/$SSH_SERVER_DIR)"
        cp "/${SSH_SERVER_DIR}"/*key* "${target}/${SSH_SERVER_DIR}"
    else
        progress "Found ssh keys in new root, skipping copy"
    fi
else
    progress "Failed to find a ssh server config on newroot partition"
    exit 1
fi

# Backup network manager connection config
if [ -d "${target}/etc/NetworkManager/system-connections" ]; then
    networks=$(ls -l "/etc/NetworkManager/system-connections/"* 2>/dev/null | wc -l)

    if [ "$networks" -gt 0 ]; then
        cp /etc/NetworkManager/system-connections/* "${target}/etc/NetworkManager/system-connections"
        progress "Copied /etc/NetworkManager/system-connections"
    fi
fi

# Backup systemd network files
if [ -d "${target}/etc/systemd/network" ]; then
    networks=$(ls -l "/etc/systemd/network/"*.network 2>/dev/null | wc -l)

    if [ "$networks" -gt 0 ]; then
        cp /etc/systemd/network/*.network "${target}/etc/systemd/network"
        progress "Copied /etc/systemd/network"
    fi
else
    progress "Failed to find a /etc/systemd/network on newroot partition"
    exit 1
fi

progress "Finished"
exit 0
