# yaml-language-server: $schema=https://raw.githubusercontent.com/siemens/kas/66261547b75885786777a0b9c8a4400ab81d432e/kas/schema-kas.json
header:
  version: 14

local_conf_header:
  meta-mender-qemu: |
    INHERIT += "mender-full"
    MENDER_ARTIFACT_NAME ?= "release-1"
    SYSTEMD_AUTO_ENABLE:pn-mender-client = "disable"
    IMAGE_FSTYPES:remove = " rpi-sdimg wic.bz2 wic.bmap"
    SDIMG_ROOTFS_TYPE = "ext4"
    MENDER_BOOT_PART_SIZE_MB = "64"
    MENDER_FEATURES_ENABLE:append = " mender-uboot"
