# yaml-language-server: $schema=https://raw.githubusercontent.com/siemens/kas/66261547b75885786777a0b9c8a4400ab81d432e/kas/schema-kas.json
header:
  version: 14

bblayers_conf_header:
  meta-minimal: |
    POKY_BBLAYERS_CONF_VERSION = "2"

local_conf_header:
  meta-minimal: |
    # Change/remove if you don't need these settings
    PACKAGE_CLASSES ?= "package_ipk"
    EXTRA_IMAGE_FEATURES ?= "debug-tweaks ssh-server-dropbear"

    # Enable the tedge feature and its underlying system configurations
    TEDGE_FEATURES_ENABLE:append = " tedge-collectd tedge-p11-kit"
    TEDGE_FEATURES_DISABLE:append = " tedge-docker"

    # systemd is recommended
    INIT_MANAGER ?= "systemd"

    # install all tedge components
    IMAGE_INSTALL:append = " sudo tedge"

    # preferred thin-edge.io version
    # Use "1.X%" if you want to use the latest from the main branch
    #PREFERRED_VERSION_tedge ?= "2.0.0"

    # Enable/Disable services by using "enable" or "disable"
    SYSTEMD_AUTO_ENABLE:mosquitto = "disable"
    SYSTEMD_AUTO_ENABLE:tedge-agent = "disable"
    SYSTEMD_AUTO_ENABLE:tedge-mapper-aws = "disable"
    SYSTEMD_AUTO_ENABLE:tedge-mapper-az = "disable"
    SYSTEMD_AUTO_ENABLE:tedge-mapper-c8y = "disable"
    SYSTEMD_AUTO_ENABLE:tedge-mapper-local = "disable"
    SYSTEMD_AUTO_ENABLE:tedge-p11-server = "disable"

    # Disable tedge-mapper-collectd mapper if collectd isn't being installed
    SYSTEMD_AUTO_ENABLE:tedge-mapper-collectd = "disable"
