# yaml-language-server: $schema=https://raw.githubusercontent.com/siemens/kas/66261547b75885786777a0b9c8a4400ab81d432e/kas/schema-kas.json
header:
  version: 14

local_conf_header:
  rugix-raspberrypi: |
    IMAGE_INSTALL:append = " kernel-image kernel-modules kernel-devicetree"

    IMAGE_FSTYPES = " tar.bz2 ext4 wic.bz2 wic.bmap"
    SDIMG_ROOTFS_TYPE = "ext4"
    WKS_FILE = "sdimage-rugix-rpi-tryboot.wks.in"
