#!/bin/sh
set -e

RAN_MARKER=/etc/tedge/.bootstrapped

log() {
    echo "$@" >&2
}

set_hostname() {
    host_name="$1"
    if [ "$(cat /etc/hostname)" = "$host_name" ]; then
        echo "Host name is already set"
        return
    fi
    echo "$host_name" | tee /etc/hostname
    sed -i -E 's/^127.0.1.1.*/127.0.1.1\t'"$host_name"'/' /etc/hosts
    hostnamectl set-hostname "$host_name"

    if command -V systemctl >/dev/null 2>&1; then
        systemctl restart avahi-daemon --no-block 2>/dev/null ||:
    fi
}

# set hostname
DEVICE_ID=
attempt=0
while [ "$attempt" -lt 30 ]; do
    DEVICE_ID="$(tedge-identity ||:)"
    if [ -n "$DEVICE_ID" ]; then
        log "Found valid DEVICE_ID"
        break
    fi
    attempt=$((attempt + 1))
    log "Waiting for tedge-identity"
    sleep 5
done

set_hostname "$DEVICE_ID"

touch "$RAN_MARKER"
