#!/bin/sh
##################################################
# Parse mender artifact to name and version
#
# Example file contents:
# ```
# core-image-tedge-mender-raspberrypi4-64_20231203.1232
# ```
##################################################
set -e

NAME=
VERSION=
BUILD_INFO_FILE=/etc/buildinfo

read_from_mender() {
    # Parse mender artifact to name and version
    # Example format: core-image-tedge-mender-raspberrypi4-64_20231203.1232
    CURRENT_ARTIFACT=$(sudo mender show-artifact 2>/dev/null ||:)

    if [ -z "$CURRENT_ARTIFACT" ]; then
        echo "mender show-artifact did not return a value" >&2
        exit 0
    fi

    NAME=$(echo "$CURRENT_ARTIFACT" | rev | cut -d_ -f2- | rev)
    VERSION=$(echo "$CURRENT_ARTIFACT" | rev | cut -d_ -f1 | rev)
}

read_from_yocto_build() {
    NAME=$(grep "IMAGE_BASENAME = " "$1" | cut -d = -f2- | xargs)
    VERSION=$(grep "IMAGE_NAME = " "$1" | cut -d = -f2- | rev | cut -d_ -f1 | rev | xargs)
}

if command -v mender >/dev/null 2>&1; then
    read_from_mender
elif [ -f "$BUILD_INFO_FILE" ]; then
    read_from_yocto_build "$BUILD_INFO_FILE"
fi

if [ -z "$NAME" ] || [ -z "$VERSION" ]; then
    echo "could not detect firmware name or version. NAME=\"$NAME\", VERSION=\"$VERSION\"" >&2
    exit 0
fi

echo "name=\"$NAME\""
echo "version=\"$VERSION\""
